# Generated by Django 5.2.8 on 2025-11-27 23:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fuera_de_zona', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('device_id', models.CharField(help_text='ID único del dispositivo del niño', max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('last_status', models.CharField(blank=True, help_text='Último estado reportado', max_length=50)),
                ('ultima_ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='monitoreo.institucion')),
            ],
        ),
    ]
