# Generated by Django 5.2.8 on 2025-11-27 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialubicacion',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='monitoreo.nino'),
        ),
        migrations.AddIndex(
            model_name='historialubicacion',
            index=models.Index(fields=['timestamp'], name='monitoreo_h_timesta_ff7217_idx'),
        ),
        migrations.AddIndex(
            model_name='historialubicacion',
            index=models.Index(fields=['fuera_de_zona'], name='monitoreo_h_fuera_d_586f21_idx'),
        ),
    ]
