# Generated by Django 5.2.8 on 2025-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='last_status',
            field=models.CharField(blank=True, help_text='Último estado reportado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nino',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
