# Generated by Django 5.2.8 on 2025-12-04 00:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_alter_nino_last_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historialubicacion',
            index=django.contrib.postgres.indexes.GistIndex(fields=['ubicacion'], name='monitoreo_h_ubicaci_ab6b87_gist'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=django.contrib.postgres.indexes.GistIndex(fields=['area'], name='monitoreo_i_area_4b674e_gist'),
        ),
    ]
