# Generated by Django 5.2.8 on 2025-12-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_historialubicacion_bateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='estado_alerta',
            field=models.CharField(choices=[('normal', 'Normal'), ('alerta_enviada', 'Alerta Enviada'), ('alerta_confirmada', 'Alerta Confirmada')], default='normal', help_text='Estado de alerta del niño', max_length=20),
        ),
    ]
