# Generated by Django 5.2.8 on 2025-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_nino_estado_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialubicacion',
            name='conexion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
