# Generated by Django 5.2.8 on 2025-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_historialubicacion_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='monitoreo_activo',
            field=models.BooleanField(default=False, help_text='Indica si el monitoreo está activo para este niño'),
        ),
    ]
